### ISSUE TITLE
Rewrite of collision detection

### ISSUE THREAD

**Issue by stijnb1234** [SBDPlugins/VehiclesPlus#78]
**Describe the bug**  
Slab driving is at the moment very buggy.

**To Reproduce**  
I tried the following combinations:

## 1:
```yml
driveOverSlabs: false
driveOverBlocks: true
vehicleDamage: false
```

This will cause a very bumpy car, that sometimes stops for slabs.

## 2:
```yml
driveOverSlabs: true
driveOverBlocks: true
vehicleDamage: false
```

This will cause slowdown issues when riding over slabs (half blocks).

## 3:
```yml
driveOverSlabs: false
driveOverBlocks: true
vehicleDamage: true
```

This will cause slowdown issues when riding over slabs (half blocks).

## 4:
```yml
driveOverSlabs: true
driveOverBlocks: true
vehicleDamage: true
```

Your vehicle will sometimes get destroyed when you are driving upward slabs.

**Expected behavior**  
It should run smoothly without any slowdown issues.

**Screenshots or Video Recordings**  
-

**Server and Plugin Information**
 - VehiclesPlus Version: 2.2.6-dev3
 - Pro or Lite? Pro
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]: PaperSpigot 1.16.5 #470
 - Operating System (if applicable): Ubuntu 20.04

**Additional context**  
-
